### ISSUE TITLE
something wrong with "confirm delete" action

### ISSUE THREAD

**Issue by 0xBa0** [WuOtto/TableViewDemo#1]
Hi Developer,

Step:
1. swipe "A" cell (showing "more" & "delete" buttons) 
2. clicked the "delete" button (showing "confirm delete" button)
3. swipe "B"(the other) cell (B is showing "more" & "delete" buttons , A's buttons are hiding)
4. clicked "B" cell's "delete" button before "A" cell hidden

Expectation: 
-> B cell will show "confirm delete" button

Actuality:
-> B cell has been deleted directly

Please kindly follow the bug if you are free.
Thanks for your sharing.

**Comment by WuOtto** [comment]
Thank you for your reply.
According to the steps you said, I did not have this problem.
[This compressed file is my operation process.](https://github.com/WuOtto/TableViewDemo/files/2711232/ScreenRecording_12-27-2018.10-20-40.MP4.zip)
My device: iPhone SE, iOS 12.0.1

If you are convenient, I hope you can provide a video of the operation.
Looking forward to your reply.

**Comment by 0xBa0** [comment]
Hi Wu,

[Please check the recording.](https://github.com/Zac-Cheung/TableViewDemo/blob/Zac-Cheung-Debug/ScreenRecording_12-27-2018%2010-34-27.mp4.zip)

My device: iPhone X, iOS 11.3

Thanks.

**Comment by WuOtto** [comment]
Ok, I know. 
I will debug this question after I get off work, thank you.

**Comment by WuOtto** [comment]
Sorry, my friend
I still haven't reproduce this problem.
My device: iPhone X, iOS 12.1.2
[ScreenRecording_12-27-2018 21-49-25.MP4.zip](https://github.com/WuOtto/TableViewDemo/files/2712549/ScreenRecording_12-27-2018.21-49-25.MP4.zip)
I don't have an iOS 11.3 device, so I may not solve this problem.
